# travis workflow:
# - static code + unit test after build (before_script)
# - run code coverage after build

cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "8"

before_script: npm test
after_success: npm run coverage

deploy: 
  provider: npm
  api_key: 
    secure: m2fWAdfhNBA6ehwAi/LdgAI1fq3+mOQtSW0Q6CNUEPmt56oLteksACPdrcRYit/SuERPT7SOC4sXvKA4qgyk4cQuKMd0sqZ+WaF3qJn25UcCDVAhXgMeA0zdAMaHUGPUexkNdP44S6zi8PLzAT7Vd+z9nfuxVXbK1LHo1nXKSYY=
  email: cpuidle@gmx.de
sudo: false
